#OR-RAMP TM2 Properties

#############################################################################################################################################################################
#
# CLUSTER PROPERTIES: MODIFY WHEN CHANGING CLUSTER CONFIGURATION OR MOVING TO NEW CLUSTER.
#
#############################################################################################################################################################################
RunModel.MatrixServerAddress=%HOST_IP_ADDRESS%
RunModel.MatrixServerPort=1191
RunModel.HouseholdServerAddress=%HOST_IP_ADDRESS%
RunModel.HouseholdServerPort= 1117


#############################################################################################################################################################################
#
# LOGGING AND DEBUGGING PROPERTIES: USE FOR TRACING HOUSEHOLDS OR AGENTS THROUGH SIMULATION.
#
#  Note that the way that logging works right now, the trace zones also have to be valid transit stops or the code will crash.  Check the skims to make sure they exist.
#  Turn off trace debugging in routine model runs to speed things up (comment out Debug.Trace.HouseholdIdList)
#
#############################################################################################################################################################################
#Resident model
Trace      = true
Trace.otaz = 0
Trace.dtaz = 0
Seek       = false
Process.Debug.HHs.Only = false
Debug.Trace.HouseholdIdList=3946
#run.this.household.only=1011947

# save tour mode choice utilities and probabilities (for debugging purpose)
TourModeChoice.Save.UtilsAndProbs = true


#############################################################################################################################################################################
#
# PATH PROPERTIES:  MODIFY AS NEEDED WHEN COPY RELEASE TO A LOCAL RUN FOLDER
#
#############################################################################################################################################################################
Project.Directory = %project.folder%
# Input path prefix
generic.path = %project.folder%
scenario.path = %project.folder%/
skims.path = %project.folder%/outputs/skims
uec.path = %project.folder%/uec/


#############################################################################################################################################################################
#
# INPUT PROPERTIES
#
#############################################################################################################################################################################

#Input Version file
Input.Version.File = LCOG_v4.ver 
#Input.Version.File = inputs/LCOG_v4.ver
