SPEC: park_and_ride_lot_choice.csv

COEFFICIENTS: park_and_ride_lot_choice_coeffs.csv

preprocessor:
  SPEC: park_and_ride_lot_choice_preprocessor.csv
  DF: df
  TABLES:
    - land_use
    - persons
    - tours
    - vehicles


LANDUSE_PNR_SPACES_COLUMN: park_and_ride_spaces

# will check the tour destination to make sure 
TRANSIT_SKIMS_FOR_ELIGIBILITY:
  - WALK_LOC_TOTALIVTT__PM

compute_settings:
  protect_columns:
  - out_period
  - in_period
