name: CI Test for Cropped Example

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Clone ActivitySim from SimOR_pnr branch
    - name: Clone ActivitySim
      run: |
        git clone --branch SimOR_pnr https://github.com/RSGInc/activitysim.git

    # Set up Miniforge and create conda environment from ActivitySim's github-actions-tests.yml
    - name: Set up Miniforge
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-version: latest
        channels: conda-forge
        activate-environment: asim-test
        python-version: "3.10"
        environment-file: activitysim/conda-environments/github-actions-tests.yml

    # Install cloned fork of ActivitySim
    - name: Install SimOR in editable mode
      run: |
        python -m pip install -e activitysim --no-deps
        conda info -a
        conda list

    # Run the test
    - name: Run cropped example test
      shell: bash -l {0}
      run: python test/test_cropped_dataset.py